[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "cd backend && python -m pip install --upgrade pip",
  "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
