[phases.setup]
nixPkgs = ["python310", "python310Packages.virtualenv", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "cd backend && /opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && /opt/venv/bin/uvicorn server:app --host 0.0.0.0 --port $PORT"
